parameters:
  nightly: false
  extra_docker_args: ""

jobs:
- job: test_linux
  displayName: Test Linux
  pool:
    vmImage: ubuntu-18.04
  container:
    image: angr/ci:2
    options: --cap-add=SYS_PTRACE --security-opt seccomp:unconfined ${{ parameters.extra_docker_args }}
  variables:
    NUM_WORKERS: 10
  strategy:
    maxParallel: 10
    matrix:
      worker_0:
        WORKER: 0
      worker_1:
        WORKER: 1
      worker_2:
        WORKER: 2
      worker_3:
        WORKER: 3
      worker_4:
        WORKER: 4
      worker_5:
        WORKER: 5
      worker_6:
        WORKER: 6
      worker_7:
        WORKER: 7
      worker_8:
        WORKER: 8
      worker_9:
        WORKER: 9

  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: "build_archive"
      targetPath: .

  - ${{ if eq(parameters.nightly, true) }}:
    - script: /root/scripts/azure-test.sh nightly
      displayName: Run nightly tests
  - ${{ if eq(parameters.nightly, false) }}:
    - script: /root/scripts/azure-test.sh
      displayName: Run standard tests

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: "JUnit"
      testResultsFiles: "build/results/*.tests.xml"
      mergeTestResults: true

  - task: PublishCodeCoverageResults@1
    condition: eq(${{ parameters.nightly }}, 'true')
    inputs:
      codeCoverageTool: "cobertura"
      summaryFileLocation: "build/results/*.coverage.xml"
      additionalCodeCoverageFiles: "build/results/*.coverage.xml"
