jobs:
- job: lint
  displayName: Lint
  pool:
    vmImage: ubuntu-16.04
  container:
    image: angr/ci:2
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: "build_archive"
      targetPath: .

  - script: /root/scripts/azure-lint.sh
    displayName: Run linter
