parameters:
  nightly: false

jobs:
- job: build_linux
  displayName: Build on Linux
  pool:
    vmImage: ubuntu-18.04
  container:
    image: angr/ci:2
  steps:
  - checkout: none

  - script: /root/scripts/azure-build.sh nightly
    condition: eq('${{ parameters.nightly }}', 'true')
    displayName: Build nightly
  - script: /root/scripts/azure-build.sh
    condition: eq('${{ parameters.nightly }}', 'false')
    displayName: Build standard

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "build_archive"
      targetPath: ./build.tar.gz
